### ISSUE TITLE
Parse AsciiUnits syntax and UnitsML

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsml-ruby#7]
Integrate code from:
* https://github.com/plurimath/plurimath/pull/112

**Comment by ronaldtse** [comment]
We also need to document the AsciiUnits syntax in the README.

**Comment by suleman-uzair** [comment]
@ronaldtse 

I’m working on converting **XML** to **UnitsML**, I’ve encountered some differences between the **XML** output I’m generating and the output generated by the **asciimath2unitsml** gem. The other conversions (**MathML**, **Unicode**, **AsciiMath**, **HTML**, and **LaTeX**) that were already provided in the **unitsdb** are complete.
I’m currently looking at the **asciimath2unitsml** gem to understand the **XML** conversion process better.
